# Generated by Django 5.0.1 on 2024-01-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('Gender', models.IntegerField(max_length=1)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('new_password', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('Reg_date', models.CharField(max_length=40)),
            ],
        ),
    ]
